export class AllCards {
    cards = [{
        logoUrl: "../../assets/splendex.png",
        whichOfPair: 1,
        isVisible: false,
        isPaired: false
    }, {
        logoUrl: "../../assets/splendex.png",
        whichOfPair: 2,
        isVisible: false,
        isPaired: false
    }, {
        logoUrl: "../../assets/angular.png",
        whichOfPair: 1,
        isVisible: false,
        isPaired: false
    }, {
        logoUrl: "../../assets/angular.png",
        whichOfPair: 2,
        isVisible: false,
        isPaired: false
    }, {
        logoUrl: "../../assets/d3.png",
        whichOfPair: 1,
        isVisible: false,
        isPaired: false
    }, {
        logoUrl: "../../assets/d3.png",
        whichOfPair: 2,
        isVisible: false,
        isPaired: false
    }, {
        logoUrl: "../../assets/jenkins.png",
        whichOfPair: 1,
        isVisible: false,
        isPaired: false
    }, {
        logoUrl: "../../assets/jenkins.png",
        whichOfPair: 2,
        isVisible: false,
        isPaired: false
    }, {
        logoUrl: "../../assets/postcss.png",
        whichOfPair: 1,
        isVisible: false,
        isPaired: false
    }, {
        logoUrl: "../../assets/postcss.png",
        whichOfPair: 2,
        isVisible: false,
        isPaired: false
    }, {
        logoUrl: "../../assets/react.png",
        whichOfPair: 1,
        isVisible: false,
        isPaired: false
    }, {
        logoUrl: "../../assets/react.png",
        whichOfPair: 2,
        isVisible: false,
        isPaired: false
    }, {
        logoUrl: "../../assets/sass.png",
        whichOfPair: 1,
        isVisible: false,
        isPaired: false
    }, {
        logoUrl: "../../assets/sass.png",
        whichOfPair: 2,
        isVisible: false,
        isPaired: false
    }, {
        logoUrl: "../../assets/ts.png",
        whichOfPair: 1,
        isVisible: false,
        isPaired: false
    }, {
        logoUrl: "../../assets/ts.png",
        whichOfPair: 2,
        isVisible: false,
        isPaired: false
    }, {
        logoUrl: "../../assets/webpack.png",
        whichOfPair: 1,
        isVisible: false,
        isPaired: false
    }, {
        logoUrl: "../../assets/webpack.png",
        whichOfPair: 2,
        isVisible: false,
        isPaired: false
    }, {
        logoUrl: "../../assets/redux.png",
        whichOfPair: 1,
        isVisible: false,
        isPaired: false
    }, {
        logoUrl: "../../assets/redux.png",
        whichOfPair: 2,
        isVisible: false,
        isPaired: false
    },
    ]
    getCards() {
        return this.cards;
    }
}